name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests on macOS
      run: swift test -v
    - name: Run tests on iOS
      run: xcodebuild -scheme MIDIKit test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'

      
